### ISSUE TITLE
windows 使用 stable-diffusion-webui 报错AttributeError: module 'os' has no attribute 'statvfs'

### ISSUE THREAD

**Issue by qianxihaoyue** [andrey-yantsen/plexiglas#14]
解决方式：
在site-packages中找到aiofiles这个包，将os.py文件中有关statvfs的代码注释掉

![image](https://github.com/andrey-yantsen/plexiglas/assets/67955603/5bcad7f1-2a60-4dd0-9775-8e7646d7ead9)

**Comment by worried-networking** [comment]
I don’t see how this is related to this project
