### ISSUE TITLE
Syncing Single Episodes - File Naming Structure

### ISSUE THREAD

**Issue by pummra** [andrey-yantsen/plexiglas#4]
Just installed the script for the first time this evening so apologies if I haven't set something up right. I ran a very quick test. When I sync a single episode the filename structure that is used on the drive includes the episode name which confuses Plex when it tries to scan the library and get the meta data. 

For example I synced one episode of Peppa Pig it synced as follows: 

/DataVolume/PlexSync/Peppa Pig - Muddy Puddles (S1 E1)/Peppa.Pig.s01e01

Plex sees that as a show called "Peppa Pig - Muddy Puddles (S1 E1)" rather than "Peppa Pig". Ideally all synced shows should only use the show title as their folder name

**Comment by worried-networking** [comment]
Thank you for the suggestion, I'll fix this within couple day.
Are you using Mobile Sync with PlexPass or `simple sync`, btw?

**Comment by pummra** [comment]
Mobile Sync with PlexPass. 

Also a quick question, it is possible as an option to split the folders in which TV Shows and Movies are synced? So that the file structure on the device is a little easier to follow?

**Comment by worried-networking** [comment]
For mobile sync you can use "special" names for sync items: when you name an item like `TV Shows#Peppa Pig` the episodes would be placed in `TV Shows` folder, etc.

**Comment by pummra** [comment]
Thanks, sorry if this is a stupid question, but where am I choosing the "special name" I can't find it within the Plex interface?

**Comment by worried-networking** [comment]
When you're creating a new "sync item" within Plex interface — it's asking you for a "title", I'm speaking about this one :) You can edit this title later in Sync settings of Plex.

-- 
Kind Regards,
Andrey Yantsen
tel: ‭+44 7564 966022‬ (mobile / telegram / whatsapp)
skype: https://join.skype.com/invite/cHqslxmGweg0 <https://join.skype.com/invite/cHqslxmGweg0>

**Comment by worried-networking** [comment]
Oh! I've just realised it. If you're using the Mobile Sync, then the folder name (in your case `Peppa Pig - Muddy Puddles (S1 E1)`) comes from Sync Item's title.
So there is nothing to fix on my side, you just need to change the title.

**Comment by pummra** [comment]
Makes, sense. Had a play with Plex and can see where to change the title. Thanks again, great app - don't know why this wasn't a standard integration built in to the drive. Makes the most sense if you already have a Plex server running!

**Comment by pummra** [comment]
Sorry, another quick question. Tried the adding the title as suggested. Which puts the files in to the TV Shows folder, however is there any way to get the show title as a folder in which the episodes go? 

So Peppa Pig would end up in: 

/DataVolume/PlexSync/TV Shows/Peppa Pig/

Might be being a bit anal about the file sturcture but this is my primary use for the drive so would end up with hundreds of files in the TV Shows folder and would be handy to have them structured a little so I can browse the files if needed.

**Comment by worried-networking** [comment]
It's not possible for now. Mainly because I haven't been able to come up with any good reason for this :) I mean, those files are maintained by `plexiglas` and can be successfully parsed by Plex.

Anyway, I actually have this thing planned, but I don't know when I'd be able to implement it properly. I'll drop you a message here whenever it'll be ready.

**Comment by pummra** [comment]
Perfect thanks. I'm just being anal about the way the files organise themselves - the main reason being if I connect the drive to my laptop and want to watch something it'd be easier to locate a file as I am planning on storing around 2TB of media on there. As long as Plex understands them that is the main thing.
