### ISSUE TITLE
Playlist syncing not working?

### ISSUE THREAD

**Issue by pummra** [andrey-yantsen/plexiglas#5]
I created a smart playlist in Plex to get the 20 latest movies which had been added and then synced that to my MyPassport drive. To test it works as expected I limited the sync to only one file. 

The file converted fine, but the download never started. I checked the plexiglas.log and looks as though it got stuck in a loop of checking sync files but never getting to the point of actually starting the download. 

Syncing a single Movie worked fine however. After I removed the sync for the smart playlist everything started working as expected. Have uploaded my log. I turned on debug logging from 10/01/2019 01:42:29, but you can see the issue starts at 10/01/2019 00:53:51. [
[plexiglas.log](https://github.com/andrey-yantsen/plexiglas/files/2744689/plexiglas.log)
](url)

**Comment by pummra** [comment]
Actually, I don't think it is a playlist issue. As I just tried syncing one movie (the same one that was at the top of the playlist) and the same issue is happening.

**Comment by worried-networking** [comment]
Which OS are you using? And what is the file system on your WD?

**Comment by pummra** [comment]
My main plex server is running on a docker in UnRaid. I haven't changed the file system on the WD, don't know what it is out of the box - but I am guessing that is likely the issue and can't have files over 4GB! 

I assume if I reformat the drive and change the file system I will need to reinstall Plexiglas?

**Comment by worried-networking** [comment]
Are you running Plexiglas directly on WD?

**Comment by pummra** [comment]
Yeah.

**Comment by worried-networking** [comment]
In this case probably I know the root of the evil... It's `:` in file name :D I'll do my best to release a new version for you today.

**Comment by pummra** [comment]
Perfect, thanks so much.

**Comment by worried-networking** [comment]
Heyhey! :) Can you please try version 0.4.0? It should be already available for you. I've added removing all disallowed characters from file names there.

Also I've added ability to split files by sub-folders, but you would need to remove the sync item first, if you'd like to try it — it can't be applied for already existent files. All you need to do is to name your sync item like `TV Show/Peppa Pig` (usual linux path-naming way).

**Comment by pummra** [comment]
Yep, already updated and tested as working. Thanks

Will also give a go to the folder splitting too, thanks again 👍
