### ISSUE TITLE
Install fails on WD Passport Pro

### ISSUE THREAD

**Issue by pummra** [andrey-yantsen/plexiglas#9]
On the latest version of pip --process-dependency-links is no longer an option so when running the install script for plexiglas it fails.

**Comment by worried-networking** [comment]
Actually this argument is not required anymore, can you give it a try without it?

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by pummra** [comment]
I'm in the middle of a sync now so can't try - sorry! 

I just downgraded pip to 18.1 and carried on as normal.

**Comment by worried-networking** [comment]
No worries then :) I’ll try it later by myself, thank you!

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen
